// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJzAR1K8AZk_Vn75yqpHyfXkjuJkfxjk',
    appId: '1:1071423953079:android:c2031a66635e7d20d15532',
    messagingSenderId: '1071423953079',
    projectId: 'imarketku-56f47',
    storageBucket: 'imarketku-56f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQ5YzFYRG0nRTNXtHbbH6LwCNFEM8-Po',
    appId: '1:1071423953079:ios:b7111b7c7acf71acd15532',
    messagingSenderId: '1071423953079',
    projectId: 'imarketku-56f47',
    storageBucket: 'imarketku-56f47.firebasestorage.app',
    iosBundleId: 'com.imarketku.apps',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJfaZ9hifjlzQ4NjJKcEHWUcdMa6Hcnto',
    appId: '1:1071423953079:web:912e6ea4fdc596a2d15532',
    messagingSenderId: '1071423953079',
    projectId: 'imarketku-56f47',
    authDomain: 'imarketku-56f47.firebaseapp.com',
    storageBucket: 'imarketku-56f47.firebasestorage.app',
    measurementId: 'G-YTDPE4QMFG',
  );

}